version: "1.0"
services:
  nginx-react:
    image: reactapp:latest
    container_name: myreactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      NODE_ENV: production
